'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.5456.
'
Namespace SyncService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FRTT_CE_SyncSoap", [Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class FRTT_CE_Sync
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New(ByVal Url As String)
            MyBase.New()
            Me.Url = Url
            Me.Timeout = 3000

        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/GetFTCount", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFTCount() As Integer
            Dim results() As Object = Me.Invoke("GetFTCount", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginGetFTCount(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFTCount", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetFTCount(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/Ping", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ping() As Boolean
            Dim results() As Object = Me.Invoke("Ping", New Object(-1) {})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginPing(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ping", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPing(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/GetFT", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFT(ByVal FTIdx As Integer) As String
            Dim results() As Object = Me.Invoke("GetFT", New Object() {FTIdx})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetFT(ByVal FTIdx As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetFT", New Object() {FTIdx}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetFT(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/GetLT", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLT() As String
            Dim results() As Object = Me.Invoke("GetLT", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetLT(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLT", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetLT(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/SaveProtocol", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveProtocol(ByVal P As String) As Boolean
            Dim results() As Object = Me.Invoke("SaveProtocol", New Object() {P})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginSaveProtocol(ByVal P As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveProtocol", New Object() {P}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSaveProtocol(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/SaveLT", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveLT(ByVal P As String) As Boolean
            Dim results() As Object = Me.Invoke("SaveLT", New Object() {P})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginSaveLT(ByVal P As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveLT", New Object() {P}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSaveLT(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/SaveTAG", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveTAG(ByVal TagID As String, ByVal PackID As Integer) As Boolean
            Dim results() As Object = Me.Invoke("SaveTAG", New Object() {TagID, PackID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Function BeginSaveTAG(ByVal TagID As String, ByVal PackID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveTAG", New Object() {TagID, PackID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSaveTAG(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/EncodeTag", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EncodeTag(ByVal TagID As String) As String
            Dim results() As Object = Me.Invoke("EncodeTag", New Object() {TagID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginEncodeTag(ByVal TagID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EncodeTag", New Object() {TagID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndEncodeTag(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/GetWMFTCount", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetWMFTCount(ByVal wmType As String, ByVal wmGroup As String) As Integer
            Dim results() As Object = Me.Invoke("GetWMFTCount", New Object() {wmType, wmGroup})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginGetWMFTCount(ByVal wmType As String, ByVal wmGroup As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetWMFTCount", New Object() {wmType, wmGroup}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetWMFTCount(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/GetWMFT", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetWMFT(ByVal wmType As String, ByVal wmGroup As String, ByVal FTIdx As Integer) As String
            Dim results() As Object = Me.Invoke("GetWMFT", New Object() {wmType, wmGroup, FTIdx})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetWMFT(ByVal wmType As String, ByVal wmGroup As String, ByVal FTIdx As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetWMFT", New Object() {wmType, wmGroup, FTIdx}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetWMFT(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
